### PR TITLE
Extra ec2 actions

### PR DESCRIPTION
**Pull request by cara-puce**
Here are some extra ec2 actions.
I thought that you should supply more than just a "stop_instance" action :)

### CODE REVIEW

**Comment by Lawouach** [comment]
Great.

However, I suggest I merge the other PR and that you rebase from master your own branch. That will keep a cleaner history. is that okay?

Also, don't forget to sign your commit (just add `-s` when you commit ;)).

**Comment by Lawouach** [comment]
The other PR is now merged into master.

**Comment by cara-puce** [comment]
Ok I think I failed my rebase, may we close this PR and make a cleaner one?

**Comment by Lawouach** [comment]
Yeah, it's probably easier :)

**Pull request closed without merging**
