### PR TITLE
adding emr probes and actions

### PR DESCRIPTION
**Pull request by joshuaroot**
- adds EMR probes 'describe_cluster', 'describe_instance_fleet', 'describe_instance_group', 'list_cluster_fleet_instances', 'list_cluster_group_instances'
- adds EMR actions 'modify_cluster', 'modify_instance_fleet', 'modify_instance_groups_instance_count', 'modify_instance_groups_shrink_policy'

Signed-off-by: Joshua Root <joshua.root@capitalone.com>

### CODE REVIEW

**Comment by joshuaroot** [comment]
@Lawouach can you look at the Travis build? I'm seeing the following:
```
>   from cryptography import x509
E   ImportError: No module named 'cryptography'
```

That should be a site-package, yes?

**Comment by Lawouach** [comment]
Feel to squash and rebase (no merge commits if we can avoid) and I'll do my best to review today.

**Comment by joshuaroot** [comment]
@Lawouach I need to look this one over a little more

**Comment by joshuaroot** [comment]
@Lawouach This one is ready for review now.

**Review by Lawouach — APPROVED** [review]
LGTM

**Pull request merged**
