### PR TITLE
init ec2_os level experiments

### PR DESCRIPTION
**Pull request by xpdable**
A new set of actions named ec2_os enables ec2 os level experiment such as burn_cpu/io/mem, network latency/loss/corruption. The actions are driven by AWS System Manager agent. Scripts from either local ones or specific Internet github or S3

### CODE REVIEW

**Comment by Lawouach** [comment]
Don't forget to sign your commits please :)

**Comment by Lawouach** [comment]
Hey @xpdable, could you squash your commits when you push to the remote branch? I am not able to review otherwise. Thanks :)

**Comment by xpdable** [comment]
> Hey @xpdable, could you squash your commits when you push to the remote branch? I am not able to review otherwise. Thanks :)

Definitely, but PR for now is not ready, will do squash and sign off when it's ready

**Comment by xpdable** [comment]
@Lawouach OK, good to review from code level. I will do UAT on our AWS.

**Comment by xpdable** [comment]
@Lawouach TBR

**Pull request closed without merging**
