### PR TITLE
New cloudwatch probes

### PR DESCRIPTION
**Pull request by javierfcamacho**
Hey guys:

I've been a bit busy the last few weeks, but I'm back!

I created a new Pull Request to clone the latest changes in the Chaos Toolkit version, adding my contribution with your latest recommendations, I hope that's all hahaha!

Let me know your comments.

### CODE REVIEW

**Comment by ciaranevans** [comment]
Hey @javierfcamacho this looks really nice!

I'm wondering if we should look at maybe not modifying the tests that didn't use `dimensions` already, if we don't specify `none` as the value of the arg, this would then at least continue to test the functions as they currently are in folks' code.

I don't see any harm in having one test where you specify it as `none`, but I think to be safe on the backwards compatibility, the rest can just be removed, considering you've put default values for them in the definition :D

**Comment by javierfcamacho** [comment]
Hey @ciaranevans!

I understand! I really did it for having a lot of test scenarios with the variable `dimensions`, but if you think that it isn't necessary, I keep it as it was originally.

**Comment by javierfcamacho** [comment]
Hey @ciaranevans! Do you have an estimated date for new release? we are in need of new features cloudwatch's probe methods 👍

**Comment by ciaranevans** [comment]
Hey @javierfcamacho ! Sorry for not updating you on this, a release came out on Oct 11!

https://github.com/chaostoolkit-incubator/chaostoolkit-aws/blob/master/CHANGELOG.md#0180---2021-10-11

**Pull request merged**
