### PR TITLE
Add extra ecs actions

### PR DESCRIPTION
**Pull request by cara-puce**
Stop given service
Stop random service (in a cluster)
Stop random service matching a filter (in a cluster)
Delete cluster
Deregister container instance

### CODE REVIEW

**Comment by cara-puce** [comment]
Unit tests and probes will come after the WE!

**Comment by Lawouach** [comment]
I'm gonna have to merge this manually I'm afraid. Too much has changed in the underlying code for this to be merged simply.

**Comment by Lawouach** [comment]
Actually not. I was mixing EC2 and ECS packages here :p

**Comment by russmiles** [comment]
Thank you @cara-puce for the contribution!

**Comment by cara-puce** [comment]
You're welcome!
I'll open few more PR in the following days/weeks regarding my needs ;)

**Comment by cara-puce** [comment]
Hey @Lawouach!
I'm already reviewing all your changes and I'll try to follow your coding style in the future (it's better than mine as I'm not so experienced with Python).
I'll keep you informed!

**Comment by Lawouach** [comment]
Thanks a lot!

Don't hesitate to join our slack as well, for faster discussion :) https://join.chaostoolkit.org/

**Pull request merged**
