### PR TITLE
asg support with basic probes

### PR DESCRIPTION
**Pull request by 0rc**
Added just the probes as I cannot think of any actions for an auto-scaling group

Signed-off-by: Dmitry Batiievskyi <dmitriy@batiyevsky.org>

### CODE REVIEW

**Comment by 0rc** [comment]
@russmiles @Lawouach are you guys vacationing? :)

**Comment by russmiles** [comment]
Apologies for delay, I’ll get on to this today.

**Comment by 0rc** [comment]
I have discovered minor issues in code we merged previously. I am finishing real-world tests and will be creating new pull request tomorrow and than we will be ready for a release I think

**Comment by russmiles** [comment]
Sounds good @0rc

**Comment by russmiles** [comment]
Maybe we could write a joint blog post on one of those real world cases post the release @0rc ?

**Pull request merged**
